feat(repair): Support getting filodb configuration at runtime.
filodb/FiloDB pull request #1098
Opened 2021-04-26 11:25 UTC by aandis

**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [x] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** Repair jobs can only retrieve configuration from a file.

**New behavior :** Building up on #1060, repair jobs will now be able to load configuration from a running FiloDB cluster by hitting an api endpoint.

2021-04-28 00:49 UTC, sherali42 approved these changes
lgtm 👍

2021-04-28 00:52 UTC, tjackpaul requested changes

2021-04-28 00:52 UTC, tjackpaul commented on spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala
> +//    conf.set("spark.filodb.partitionkeys.copier.source.config.endpoint", "http://localhost:9090/__confi")
NiT: Remove if not needed

2021-04-28 18:01 UTC, vishramachandran commented
Abhishek and I had an offline conversation on this PR. There may be a different solution to explore. Let us put this PR on hold.

2021-05-07 15:13 UTC, vishramachandran approved these changes

2021-05-07 16:59 UTC, tjackpaul approved these changes

2021-05-07 17:18 UTC, merged