perf(core) Lucene field reuse
filodb/FiloDB pull request #1169
Opened 2021-07-21 20:10 UTC by vishramachandran

**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

Reuse lucene fields to reduce allocation during Index bootstrapping.
For dynamic fields, using a weak hash map to cache the fields.

2021-07-22 23:53 UTC, sherali42 requested changes
we should add charset to `new String`

2021-07-22 23:53 UTC, sherali42 commented on core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
> +          val value = new String(base.asInstanceOf[Array[Byte]], strOffset.toInt - UnsafeUtils.arayOffset, numBytes)
we would need `Charset` here?

2021-07-23 18:24 UTC, vishramachandran commented on core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
> +          val value = new String(base.asInstanceOf[Array[Byte]], strOffset.toInt - UnsafeUtils.arayOffset, numBytes)
good point

2021-07-23 18:38 UTC, vishramachandran commented on core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
> +          val value = new String(base.asInstanceOf[Array[Byte]], strOffset.toInt - UnsafeUtils.arayOffset, numBytes)
added

2021-07-23 18:39 UTC, vishramachandran commented
Ran all unit tests locally

2021-07-23 18:45 UTC, sherali42 approved these changes
👍

2021-07-24 00:26 UTC, merged