feat(query): support for subqueries in MultiPartitionPlanner and Shar…
filodb/FiloDB pull request #1205
Opened 2021-08-27 01:50 UTC by kvpetrov

…kKeyRegexPlanner

**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

Breaking changes may include:
- Any schema changes to any Cassandra tables
- The serialized format for Dataset and Column (see .toString methods)
- Over the wire formats for Akka messages / case classes
- Changes to the HTTP public API
- Changes to query parsing / PromQL parsing

**Other information**:

2021-09-01 21:22 UTC, vishramachandran requested changes
Thank you for the changes. Please see comments.

2021-09-02 20:37 UTC, kvpetrov commented on coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
> +  it("should direct subquery with windowing to downsample planner and verify subquery lookback") {
the cases already exist (that was the part of the previous PR, this PR dealt only with the last case):
"should direct raw-cluster-only range function subqueries to raw planner"
"should directed downsample-only range function subqueries to downsample planner"
""should direct subquery with windowing to downsample planner and verify subquery lookback"

2021-09-02 22:28 UTC, kvpetrov commented on coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
> +  it("should generate Exec plan for subquery with windowing") {
fixed

2021-09-02 23:23 UTC, vishramachandran approved these changes

2021-09-02 23:24 UTC, merged