maint(core, query): Upgrade to Monix 3.4.0; Monix-kafka 1.0.0-RC6
filodb/FiloDB pull request #1324
Opened 2022-01-24 13:34 UTC by vishramachandran

**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

Monix library version upgrade. Here are notable changes:

* runAsync rename to runToFuture used in many places
* Many other method renames, some to include "unsafe" suffix to indicate that dual consumption may be an issue.
* monix kafka custom changes not needed anymore. Latest version works for us
* [needs performance testing] Thread assertions required me to use the AlwaysAsync execution model on query threads to avoid query tasks running on Akka scheduler.
* [needs performance testing] Some tasks required cats IO usage. This is new
* [needs performance testing] Some lambdas required new tasks to be created with Task.now

TODO:
* Thread assertions are disabled in unit tests. Some new ones may pop in environment testing
* JMH Benchmarks need to be run. Will run the important ones before merging PR
* Need to pay closer attention to dual consumption from observable (I think during ODP)

2022-01-24 20:49 UTC, alextheimer approved these changes
Thank you for the heads-up.

2022-01-24 21:36 UTC, amolnayak311 requested changes
Some comments left, also tests fail.

2022-01-27 04:48 UTC, vishramachandran commented on coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
> +      ExecutionModel.AlwaysAsyncExecution)
This is now fixed. Thanks much for the team work on identifying that Task.apply changed from being async to synchronous in the new monix release. With that AlwaysAsync is not needed.

2022-01-27 04:52 UTC, vishramachandran commented on core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
> +    }.mapParallelOrdered(parallelism) { pk => // preserve order so updates get applied correctly
In theory, downsample part key index update stream can contain dupes, so order is important.
However I realize, dupes are far apart, so Unordered should suffice here. Will change

2022-02-02 22:43 UTC, amolnayak311 approved these changes
LGTM

2022-02-02 22:49 UTC, merged