fix(core) message use histogram_quantile for max(histogram) queries.
filodb/FiloDB pull request #1539
Opened 2023-03-23 21:23 UTC by yu-shipit

max(histogram) is not supported histogram_quantile(1, histogram) may be what users want.

**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

Breaking changes may include:
- Any schema changes to any Cassandra tables
- The serialized format for Dataset and Column (see .toString methods)
- Over the wire formats for Akka messages / case classes
- Changes to the HTTP public API
- Changes to query parsing / PromQL parsing

**Other information**:

2023-03-23 21:28 UTC, yu-shipit commented
max(histogram) will the the message below.
```
{
  "status" : "error",
  "data" : null,
  "errorType" : "requirement_failed",
  "error" : "max(histogram expr) is not supported. You may use histogram_quantile(1, histogram expr) instead.",
  "queryStats" : [ {
    "group" : [ "local", "raw", "aci-telemetry", "Test-data-1679598622_p1", "my_histogram" ],
    "timeSeriesScanned" : 2,
    "dataBytesScanned" : 259,
    "resultBytes" : 0,
    "cpuNanos" : 0
  } ]
}
```

2023-03-23 21:49 UTC, alextheimer approved these changes
Thanks @yu-shipit for digging into this unexpectedly-complex problem 👍

2023-03-24 02:22 UTC, amolnayak311 commented
1. If the behavior differs from Prometheus we need to call it out explicitly, in the PR and also a comment in the code as we generally strive to maintain compatibility as far as possible. 
2. It is important for the user to understand that histogram_quantile will give the approximation  which is dependent on their buckets, while the user might be expecting to see the max value recorded.

2023-03-29 16:22 UTC, amolnayak311 commented on query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala
> +      case Min if valColType == ColumnType.DoubleColumn => MinRowAggregator
Do you see any case where `LongColumn` and `IntColumn` would need this? I understand we don't want to use this for histograms but by restricting to DoubleColumn only we also don't support Long and Int columns

2023-03-29 16:37 UTC, amolnayak311 approved these changes

2023-03-29 17:41 UTC, vishramachandran requested changes
Asking for a small change in error message

2023-03-29 17:41 UTC, vishramachandran commented on query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala
> +      s" Because it does not result in a meaningful query. Please contact us if you have a use case.")
Let us not use this message as fallback for all.
For histograms:
> "The ${aggrOp} operation is not supported directly for histogram types. Check if you need to resolve to the individual histogram buckets, or calculate the rate and histogram_quantile before applying the aggregation. If you have a genuine use case for this query, please get in touch."


For doubles, it should be an illegal state exception. It should be unreachable code.

2023-03-29 17:43 UTC, vishramachandran commented on query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala
> +      s" Because it does not result in a meaningful query. Please contact us if you have a use case.")
Count_values should also be applied only to doubles.

2023-03-29 20:43 UTC, vishramachandran approved these changes
LGTM. thank you!!

2023-03-29 20:47 UTC, merged