Trailing comma functionality for Queries
filodb/FiloDB pull request #1608
Opened 2023-06-14 18:15 UTC by Arhanace

2023-06-16 19:06 UTC, alextheimer requested changes

2023-06-16 19:06 UTC, alextheimer commented on prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
> +    parseSuccessfully("sum by(and, by, avg, count, alert, annotations, )(some_metric)")
Could you add a couple for binary joins (i.e. `+`/`-`/`and`, etc), as well? The analogous clauses are `on` and `ignoring`, and the label lists used for each are called "`labelNameList`" in the grammar (I am not sure offhand why we allow more complex expressions in an aggregation's clause).

2023-06-16 20:43 UTC, alextheimer approved these changes

2023-06-16 20:43 UTC, alextheimer commented on prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
> +    parseSuccessfully("sum by(and, by, avg, count, alert, annotations, )(some_metric)")
Ah I see I was confused -- `labelNameList` is the one you already updated, and `parameterList` has nothing to do with a `by`/`without` clause:
```
aggregation
    : AGGREGATION_OP parameterList
    | AGGREGATION_OP (by | without) parameterList
    | AGGREGATION_OP parameterList ( by | without)
    ;
by:      BY labelNameList;
without: WITHOUT labelNameList;
```

Cool, I thought we needed more updates to the grammar but that's not the case.

2023-06-16 20:43 UTC, alextheimer commented on prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
> +    parseSuccessfully("foo - on(test,blub,) group_right(bar,foo,) bar")
Excellent call with these `group` clauses 👍

2023-06-20 16:24 UTC, yu-shipit commented on prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
> +    parseSuccessfully("foo and ignoring(test,blub,) bar")
should we also add tests for the no trailing comma case?

2023-06-26 21:42 UTC, amolnayak311 commented
Please follow https://github.com/filodb/FiloDB/blob/develop/CONTRIBUTING.md for PR title and summarize the PR changes. Also congratulation on your first PR.

2023-06-28 18:09 UTC, merged