add grammar support for @modifier.
filodb/FiloDB pull request #1670
Opened 2023-09-15 15:33 UTC by yu-shipit

**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

Breaking changes may include:
- Any schema changes to any Cassandra tables
- The serialized format for Dataset and Column (see .toString methods)
- Over the wire formats for Akka messages / case classes
- Changes to the HTTP public API
- Changes to query parsing / PromQL parsing

**Other information**:

2023-09-16 22:06 UTC, alextheimer requested changes
LGTM, just one small update requested in the comments-- please feel free to dismiss this review after that's updated.

2023-09-16 22:06 UTC, alextheimer commented on prometheus/src/main/java/filodb/prometheus/antlr/PromQL.g4
> +modifier: offset | atModifier | offset atModifier | atModifier offset;
https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier

2023-09-16 22:37 UTC, alextheimer submitted a review, later dismissed
Approved for the sake of forward progress -- please feel free to merge after the other comments are addressed.

2023-09-19 18:55 UTC, yu-shipit commented on prometheus/src/main/java/filodb/prometheus/antlr/PromQL.g4
> +modifier: offset | atModifier | offset atModifier | atModifier offset;
good catch. It seems the white space is optional.
http://demo.robustperception.io:9090/graph?g0.expr=topk(5%2C%20rpc_durations_histogram_seconds_bucket%7Binstance%3D%22demo.do.prometheus.io%3A8996%22%7D%20%40start())&g0.tab=0&g0.stacked=0&g0.range_input=1d&g1.expr=%20max(rpc_durations_histogram_seconds_bucket%7Binstance%3D%22demo.do.prometheus.io%3A8996%22%7D)%20&g1.tab=0&g1.stacked=0&g1.range_input=1h&g2.expr=rpc_durations_histogram_seconds_bucket%7Binstance%3D%22demo.do.prometheus.io%3A8996%22%2C%20job%3D%22random%22%2C%20le%3D%22%2BInf%22%7D&g2.tab=0&g2.stacked=0&g2.range_input=1h

2023-09-19 22:55 UTC, yu-shipit commented on prometheus/src/main/java/filodb/prometheus/antlr/PromQL.g4
> +modifier: offset | atModifier | offset atModifier | atModifier offset;
It seems the parser can naturally handle both cases. added @ start() and @start() to the tests.

2023-09-29 17:41 UTC, alextheimer approved these changes
Thanks for the additional tests @yu-shipit 🙏

2023-09-29 17:56 UTC, merged